#!/bin/bash
echo "enter three numbers"
read num1
read num2
read num3
if [ $num1 -gt $num2 -a $num1 -gt $num3 ]
then
echo "$num1 is greater"
elif [ $num2 -gt $num3 ]
then
echo "$num2 is greater"
else
echo "$num3 is greater"
fi







output
enter three numbers
1
2
3
3 is greater
